#version: 0.0 # CodeDeploy 버전 0.0외 다른버전 사용시 오류발생
#os: linux
#files:
#  - source: / # CodeDeploy에서 전달해준 파일중 destination으로 이동할 대상을 지정. 루트(/)지정시 전체파일 옮겨짐
#    destination: /home/ec2-user/app/step2/zip/ # source에서 지정한 파일을 받을 위치
#    overwrite: yes # 기존에 파일이 있으면 덮어쓰기
#
#permissions: # codedeploy가 ec2로 넘겨준 파일을 ec2-user 권한을 갖도록함
#  - obejct: /
#    pattern: "**"
#    owner: ec2-user
#    group: ec2-user
##codedeploy 배포단계에서 실행할 명령어지정
#hooks:
#  ApplicationStart: # 이 단계에서
#    - location: deploy.sh # 이파일을
#      timeout: 60 # 60초이상 걸릴시 실패로 처리
#      runas: ec2-user # 이 권한으로 실행

version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작합니다.
      timeout: 60
      runas: ec2-user